import { Router } from "express";

// Served as plain, server-rendered HTML, not part of the React SPA, so
// these are reachable even if the JS bundle fails to load, and so they can
// be linked from anywhere (Stripe checkout, emails) without depending on
// client-side routing. Mounted in app.ts BEFORE the SPA catch-all.
//
// IMPORTANT: the Terms and Privacy pages below are a starting draft, not a
// finished legal document. They're grounded in what the app actually does
// today (see the comments below each section), but every [FILL IN: ...]
// marker needs a real answer, and the whole thing needs review by an
// actual lawyer before it's something to rely on, especially given real
// payment processing is live. Treat this as the first draft to hand to
// that review, not the final artifact. The About page has no such
// disclaimer: it's plain product copy, not a legal document.

const PAGE_STYLE = `
  body { font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif; max-width: 720px; margin: 0 auto; padding: 40px 24px 80px; line-height: 1.6; color: #1a1a1a; }
  h1 { font-size: 1.6rem; margin-bottom: 4px; }
  h2 { font-size: 1.15rem; margin-top: 2rem; }
  .draft-banner { background: #fff3cd; border: 1px solid #d9a441; border-radius: 8px; padding: 14px 16px; margin: 20px 0 32px; font-size: 0.95rem; }
  .draft-banner strong { display: block; margin-bottom: 4px; }
  .fill-in { background: #ffe0e0; padding: 1px 4px; border-radius: 3px; font-weight: 600; }
  .updated { color: #666; font-size: 0.9rem; }
  a { color: #4a3aff; }
`;

function page(title: string, bodyHtml: string, showDraftBanner = true): string {
  return `<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <title>${title} · Spark</title>
  <style>${PAGE_STYLE}</style>
</head>
<body>
  ${showDraftBanner ? `<div class="draft-banner">
    <strong>Draft. Not final, not legal advice.</strong>
    This document has not been reviewed by a lawyer and is not yet in effect. Fields marked
    <span class="fill-in">like this</span> still need real answers before this page should be
    relied on or linked from signup/checkout.
  </div>` : ""}
  ${bodyHtml}
</body>
</html>`;
}

export const legalPagesRouter = Router();

legalPagesRouter.get("/terms", (_req, res) => {
  res.send(page("Terms of Service", `
    <h1>Terms of Service</h1>
    <p class="updated">Draft, not yet in effect.</p>

    <h2>1. Who this agreement is with</h2>
    <p>
      Spark ("we", "us") is operated by <span class="fill-in">[FILL IN: legal entity name, or
      your name if operating as an individual]</span>, based in
      <span class="fill-in">[FILL IN: country/state]</span>. Questions about these terms can be
      sent to <span class="fill-in">[FILL IN: contact email]</span>.
    </p>

    <h2>2. The service</h2>
    <p>
      Spark is a tabletop RPG prep-and-play companion: generators for characters, items,
      locations, and more; a roster and world system to organize what you save; and a live,
      real-time combat/chat companion for running sessions with your table. Every generator is
      deterministic and hand-curated. Nothing you create is sent to or generated by a language
      model. (The app itself is built with the help of AI-assisted development tools; see the
      <a href="/about">About page</a> for what that does and doesn't mean.)
    </p>

    <h2>3. Accounts</h2>
    <p>
      You're responsible for keeping your account credentials secure and for what happens under
      your account. You must be at least <span class="fill-in">[FILL IN: minimum age, commonly
      13 in the US under COPPA, sometimes 16 depending on jurisdiction; confirm the right
      threshold]</span> years old to create an account.
    </p>

    <h2>4. Your content</h2>
    <p>
      Content you create (worlds, characters, session notes, and everything else you save) is
      yours. By using shared features (inviting players to a world, publishing to the public
      Gallery), you're granting the people you share it with the access those features imply.
      Content published to the public Gallery is visible to other users and subject to our
      moderation and reporting process; we may remove content that violates
      <span class="fill-in">[FILL IN: link to or define community guidelines, if any beyond what
      exists in-app]</span>.
    </p>

    <h2>5. Paid subscriptions</h2>
    <p>
      Paid tiers are billed through Stripe on a recurring basis until cancelled. You can manage
      or cancel your subscription at any time from your account.
      <span class="fill-in">[FILL IN: refund policy, e.g. no refunds for partial billing
      periods, or your actual policy]</span>.
    </p>

    <h2>6. Account deletion</h2>
    <p>
      You can permanently delete your account and its data at any time from your account
      settings, after confirming your password. Deletion is immediate, not a grace period — your
      account and everything tied to it (worlds, characters, session notes, and everything else)
      is removed from the live database right away. As noted in the Privacy Policy §5, deleted
      data may still exist in disaster-recovery backups until those age out, on a rolling 14-day
      window.
    </p>

    <h2>7. Disclaimers and liability</h2>
    <p><span class="fill-in">[FILL IN: standard "as-is" disclaimer, limitation of liability, and
      governing law clause. This section in particular should not be written without a lawyer,
      since it's the part doing the actual legal protection]</span>.
    </p>

    <h2>8. Changes to these terms</h2>
    <p>
      We may update these terms as the service changes. <span class="fill-in">[FILL IN: how
      you'll notify users of material changes]</span>.
    </p>
  `));
});

legalPagesRouter.get("/privacy", (_req, res) => {
  res.send(page("Privacy Policy", `
    <h1>Privacy Policy</h1>
    <p class="updated">Draft, not yet in effect.</p>

    <h2>1. What we collect</h2>
    <p>
      An account requires a username and a password (stored as a salted hash, never in plain
      text) and generates a one-time account-recovery code (also stored hashed). A display name
      is optional. Everything else you create, including worlds, characters, session notes, chat
      messages, and dice rolls, is stored so the app can show it back to you and to whoever
      you've shared it with.
    </p>

    <h2>2. Payment information</h2>
    <p>
      Paid subscriptions are processed by Stripe. We never see or store your card number. Stripe
      handles the payment form directly, and we only receive a subscription status and a
      customer reference from them.
    </p>

    <h2>3. What we don't do</h2>
    <p>
      Nothing you create is sent to or processed by a third-party AI or language model. Every
      generator in Spark is deterministic and hand-curated. We don't sell your data, and we don't
      use your campaign content for anything other than showing it back to you and the people
      you've explicitly shared it with. (Separately: the app itself was built with the help of
      AI-assisted development tools. That's a fact about how we write code, not about what
      happens to your data. See the <a href="/about">About page</a> for the distinction.)
    </p>

    <h2>4. Cookies</h2>
    <p>
      We use a single authentication cookie to keep you signed in. We don't use third-party
      advertising or tracking cookies, and no analytics tool is integrated into the app today.
      If that changes, this section will be updated first.
    </p>

    <h2>5. Backups</h2>
    <p>
      We keep encrypted backups of the database for disaster-recovery purposes, retained on a
      rolling 14-day window (the most recent 14 daily backups; older ones are automatically
      deleted). Deleting your account removes your data from the live database immediately; it
      may persist in backups until they age out of that 14-day window.
    </p>

    <h2>6. Who we share data with</h2>
    <p>
      Only the infrastructure providers needed to run the service: Render for hosting, Stripe
      for payment processing, and Cloudflare (R2) for backup storage. None of them use your data
      for anything beyond providing that infrastructure to us.
    </p>

    <h2>7. Your rights</h2>
    <p>
      You can view, edit, or delete any of your content at any time from within the app, and you
      can permanently delete your account and its data from your account settings.
      <span class="fill-in">[FILL IN: if you have users in the EU/UK or California, add GDPR/CCPA
      specific rights language here. This needs legal review to get right]</span>.
    </p>

    <h2>8. Contact</h2>
    <p>
      Questions about this policy: <span class="fill-in">[FILL IN: contact email]</span>.
    </p>
  `));
});

legalPagesRouter.get("/about", (_req, res) => {
  res.send(page("About", `
    <h1>About Spark</h1>

    <h2>What Spark is</h2>
    <p>
      Spark is a tabletop RPG prep-and-play companion: generators for characters, items,
      locations, quests, and more; a roster and world system to organize what you build; and a
      live, real-time combat and chat companion for running sessions at the table.
    </p>

    <h2>How the generators work</h2>
    <p>
      Every generator draws from hand-built content pools, not a live call to a language model.
      Nothing you generate is scraped prose or laundered from a model's training data. The name
      is the point: click Generate and you get a spark, a starting idea meant to move your own
      imagination, not a finished product handed to you. From there the choice is entirely
      yours. Keep it exactly as it came out, rewrite every word, or land anywhere in between.
    </p>

    <h2>How this app was built</h2>
    <p>
      We're upfront about this rather than staying quiet on it: Spark's own codebase was built
      with the help of AI-assisted development tools. That's a separate question from what
      happens to your content, which is answered above. We think there's a real difference
      between a tool that helps a developer write software and a tool that generates the
      creative content you put in front of your players, and we don't think using the first one
      means we should pretend the second one doesn't matter. Used well, we think AI is a
      force multiplier for the person building a thing, not a replacement for the person
      imagining what to build. That's the same philosophy this product is built to hand off to
      you: a spark, not a script.
    </p>

    <h2>Where your data goes</h2>
    <p>
      Nothing you create is sent to a third-party AI or language model, sold, or used for
      anything beyond showing it back to you and the people you've explicitly shared it with.
      Full details are in the <a href="/privacy">Privacy Policy</a>.
    </p>
  `, false));
});

legalPagesRouter.get("/faq", (_req, res) => {
  res.send(page("FAQ", `
    <h1>Frequently Asked Questions</h1>

    <h2>Is Spark free?</h2>
    <p>
      Yes. A free account can run up to 3 worlds, with full access to the generators, roster,
      and live play tools, including real-time combat, chat, and party sync, which aren't
      gated behind a paid tier. Upgrading ($4.99/mo) removes the world limit. See the
      <a href="/privacy">Privacy Policy</a> for how payment is handled.
    </p>

    <h2>Are the generators powered by AI?</h2>
    <p>
      No. Every generator draws from hand-built content pools, not a live call to a language
      model. Nothing you generate is scraped prose or laundered from a model's training data.
      More on the philosophy behind that in the <a href="/about">About page</a>.
    </p>

    <h2>Does any of my campaign content get used to train AI?</h2>
    <p>
      No. Nothing you create is sent to or processed by a third-party AI or language model,
      sold, or used for anything beyond showing it back to you and the people you've explicitly
      shared it with. (Separately, Spark's own codebase was built with the help of AI-assisted
      development tools. That's a fact about how we write code, not about what happens to your
      data. See the <a href="/about">About page</a> for the distinction.)
    </p>

    <h2>How do my players join a world?</h2>
    <p>
      From the Worlds screen, share your world's join code with your players. They enter it
      under "Join World" to get access. Once in, encounters, dice rolls, HP, chat, and party
      inventory all sync live to everyone at the table.
    </p>

    <h2>I forgot my password. Now what?</h2>
    <p>
      Spark doesn't require an email address, so password resets work through a one-time
      account-recovery code instead. You're shown that code once, when you create your account
      (and again any time you regenerate it from your account settings), so save it somewhere
      safe. On the login screen, choose "Forgot password?" and enter your username and recovery
      code to set a new password.
    </p>

    <h2>Can I use Spark on my phone during a session?</h2>
    <p>
      Yes. The app can be installed to your phone's home screen like a native app, and the
      interface it loads is cached so it still comes up even on a spotty connection. Live
      features like combat sync and chat still need a working connection to actually update.
    </p>

    <h2>Can I delete my account?</h2>
    <p>
      Yes, at any time from your account settings. See the <a href="/privacy">Privacy Policy</a>
      for what that does and doesn't remove.
    </p>

    <h2>Where do I read the fine print?</h2>
    <p>
      The <a href="/terms">Terms of Service</a> and <a href="/privacy">Privacy Policy</a> cover
      the legal details. This page is just a plain-language summary.
    </p>
  `, false));
});
