import { Router } from "express";

// Served as plain, server-rendered HTML — not part of the React SPA — so
// these are reachable even if the JS bundle fails to load, and so they can
// be linked from anywhere (Stripe checkout, emails) without depending on
// client-side routing. Mounted in app.ts BEFORE the SPA catch-all.
//
// IMPORTANT: this is a starting draft, not a finished legal document. It's
// grounded in what the app actually does today (see the comments below
// each section), but every [FILL IN: ...] marker needs a real answer, and
// the whole thing needs review by an actual lawyer before it's something
// to rely on — especially given real payment processing is live. Treat
// this as the first draft to hand to that review, not the final artifact.

const PAGE_STYLE = `
  body { font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif; max-width: 720px; margin: 0 auto; padding: 40px 24px 80px; line-height: 1.6; color: #1a1a1a; }
  h1 { font-size: 1.6rem; margin-bottom: 4px; }
  h2 { font-size: 1.15rem; margin-top: 2rem; }
  .draft-banner { background: #fff3cd; border: 1px solid #d9a441; border-radius: 8px; padding: 14px 16px; margin: 20px 0 32px; font-size: 0.95rem; }
  .draft-banner strong { display: block; margin-bottom: 4px; }
  .fill-in { background: #ffe0e0; padding: 1px 4px; border-radius: 3px; font-weight: 600; }
  .updated { color: #666; font-size: 0.9rem; }
  a { color: #4a3aff; }
`;

function page(title: string, bodyHtml: string): string {
  return `<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <title>${title} — Spark</title>
  <style>${PAGE_STYLE}</style>
</head>
<body>
  <div class="draft-banner">
    <strong>Draft — not final, not legal advice.</strong>
    This document has not been reviewed by a lawyer and is not yet in effect. Fields marked
    <span class="fill-in">like this</span> still need real answers before this page should be
    relied on or linked from signup/checkout.
  </div>
  ${bodyHtml}
</body>
</html>`;
}

export const legalPagesRouter = Router();

legalPagesRouter.get("/terms", (_req, res) => {
  res.send(page("Terms of Service", `
    <h1>Terms of Service</h1>
    <p class="updated">Draft — not yet in effect.</p>

    <h2>1. Who this agreement is with</h2>
    <p>
      Spark ("we", "us") is operated by <span class="fill-in">[FILL IN: legal entity name, or
      your name if operating as an individual]</span>, based in
      <span class="fill-in">[FILL IN: country/state]</span>. Questions about these terms can be
      sent to <span class="fill-in">[FILL IN: contact email]</span>.
    </p>

    <h2>2. The service</h2>
    <p>
      Spark is a tabletop RPG prep-and-play companion: generators for characters, items,
      locations, and more; a roster and world system to organize what you save; and a live,
      real-time combat/chat companion for running sessions with your table. Every generator is
      deterministic and hand-curated — nothing you create is sent to or generated by a language
      model.
    </p>

    <h2>3. Accounts</h2>
    <p>
      You're responsible for keeping your account credentials secure and for what happens under
      your account. You must be at least <span class="fill-in">[FILL IN: minimum age — commonly
      13 in the US under COPPA, sometimes 16 depending on jurisdiction; confirm the right
      threshold]</span> years old to create an account.
    </p>

    <h2>4. Your content</h2>
    <p>
      Content you create — worlds, characters, session notes, and everything else you save — is
      yours. By using shared features (inviting players to a world, publishing to the public
      Gallery), you're granting the people you share it with the access those features imply.
      Content published to the public Gallery is visible to other users and subject to our
      moderation and reporting process; we may remove content that violates
      <span class="fill-in">[FILL IN: link to or define community guidelines, if any beyond what
      exists in-app]</span>.
    </p>

    <h2>5. Paid subscriptions</h2>
    <p>
      Paid tiers are billed through Stripe on a recurring basis until cancelled. You can manage
      or cancel your subscription at any time from your account.
      <span class="fill-in">[FILL IN: refund policy — e.g. no refunds for partial billing
      periods, or your actual policy]</span>.
    </p>

    <h2>6. Account deletion</h2>
    <p>
      You can permanently delete your account and its data at any time from your account
      settings. <span class="fill-in">[FILL IN: confirm exact deletion behavior — immediate vs.
      grace period, and whether backups are excluded from the deletion (see Privacy Policy §5) —
      to be certain this section matches what the account-deletion feature actually does]</span>.
    </p>

    <h2>7. Disclaimers and liability</h2>
    <p><span class="fill-in">[FILL IN: standard "as-is" disclaimer, limitation of liability, and
      governing law clause — this section in particular should not be written without a lawyer,
      since it's the part doing the actual legal protection]</span>.
    </p>

    <h2>8. Changes to these terms</h2>
    <p>
      We may update these terms as the service changes. <span class="fill-in">[FILL IN: how
      you'll notify users of material changes]</span>.
    </p>
  `));
});

legalPagesRouter.get("/privacy", (_req, res) => {
  res.send(page("Privacy Policy", `
    <h1>Privacy Policy</h1>
    <p class="updated">Draft — not yet in effect.</p>

    <h2>1. What we collect</h2>
    <p>
      An account requires a username and a password (stored as a salted hash, never in plain
      text) and generates a one-time account-recovery code (also stored hashed). A display name
      is optional. Everything else you create — worlds, characters, session notes, chat
      messages, dice rolls — is stored so the app can show it back to you and to whoever you've
      shared it with.
    </p>

    <h2>2. Payment information</h2>
    <p>
      Paid subscriptions are processed by Stripe. We never see or store your card number — Stripe
      handles the payment form directly and we only receive a subscription status and a customer
      reference from them.
    </p>

    <h2>3. What we don't do</h2>
    <p>
      Nothing you create is sent to or processed by a third-party AI or language model — every
      generator in Spark is deterministic and hand-curated. We don't sell your data, and we don't
      use your campaign content for anything other than showing it back to you and the people
      you've explicitly shared it with.
    </p>

    <h2>4. Cookies</h2>
    <p>
      We use a single authentication cookie to keep you signed in. We don't use third-party
      advertising or tracking cookies.
      <span class="fill-in">[FILL IN: confirm this is accurate, and add an analytics disclosure
      here if/when any analytics tool is added]</span>.
    </p>

    <h2>5. Backups</h2>
    <p>
      We keep encrypted backups of the database for disaster-recovery purposes, retained for a
      rolling window of <span class="fill-in">[FILL IN: confirm retention window — currently 14
      days by default]</span>. Deleting your account removes your data from the live database;
      it may persist in backups until they age out of that window.
    </p>

    <h2>6. Who we share data with</h2>
    <p>
      Only the infrastructure providers needed to run the service: <span class="fill-in">[FILL
      IN: name your hosting provider]</span> for hosting, Stripe for payment processing, and
      Cloudflare (R2) for backup storage. None of them use your data for anything beyond
      providing that infrastructure to us.
    </p>

    <h2>7. Your rights</h2>
    <p>
      You can view, edit, or delete any of your content at any time from within the app, and you
      can permanently delete your account and its data from your account settings.
      <span class="fill-in">[FILL IN: if you have users in the EU/UK or California, add GDPR/CCPA-
      specific rights language here — this needs legal review to get right]</span>.
    </p>

    <h2>8. Contact</h2>
    <p>
      Questions about this policy: <span class="fill-in">[FILL IN: contact email]</span>.
    </p>
  `));
});
